// GENERATED by `dart run flutter_assistant_intents:generate` — DO NOT EDIT.
// Source of truth: assistant_intents.yaml

import 'package:flutter_assistant_intents/flutter_assistant_intents.dart';

/// Action id of "Clear Completed Tasks" — handle it in `onAction`.
const String clearCompletedAction = 'clear_completed';

/// Android shortcuts declared in assistant_intents.yaml.
/// Pass to `AssistantIntents.instance.updateShortcuts`.
const AndroidShortcutsConfig generatedAndroidShortcuts = AndroidShortcutsConfig(
  publishTaskShortcuts: true,
  addTaskLabel: 'Add task',
  queryTodayLabel: 'Today',
  customShortcuts: [
    AndroidCustomShortcut(
      id: 'clear_completed',
      action: 'clear_completed',
      shortLabel: 'Clean up',
      longLabel: 'Clear completed tasks',
    ),
  ],
);
