// GENERATED by `dart run flutter_assistant_intents:generate` — DO NOT EDIT.
// Source of truth: assistant_intents.yaml

import AppIntents
import flutter_assistant_intents

/// Removes all completed tasks from the list.
@available(iOS 16.0, *)
struct ClearCompletedIntent: AppIntent {
    static var title: LocalizedStringResource = "Clear Completed Tasks"
    static var description = IntentDescription("Removes all completed tasks from the list.")
    static var openAppWhenRun: Bool = false

    func perform() async throws -> some IntentResult & ProvidesDialog {
        let result = try await AssistantIntentBridge.shared.performAction(id: "clear_completed")
        return .result(dialog: IntentDialog(stringLiteral:
            result.message ?? (result.success ? "Done." : "Sorry, that failed.")
        ))
    }
}

/// Re-exports the plugin's built-in task intents so App Intents metadata
/// extraction finds them (requires iOS 17 at runtime for the re-export).
@available(iOS 17.0, *)
struct GeneratedAppIntentsPackage: AppIntentsPackage {
    static var includedPackages: [any AppIntentsPackage.Type] {
        [FlutterAssistantIntentsPackage.self]
    }
}

/// Siri phrases for the generated intents.
@available(iOS 16.0, *)
struct GeneratedAppShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        AppShortcut(
            intent: ClearCompletedIntent(),
            phrases: [
                "Clean up my tasks in \(.applicationName)",
                "Clear completed tasks in \(.applicationName)",
            ],
            shortTitle: "Clean Up",
            systemImageName: "trash.circle"
        )
    }
}
